layout_spectrum: 0.8810623
typography_spectrum: 0.9665603
color:
  lightness: 0.7706577
  brandStrength: 0.2856645
  saturation: 0.7175379
  rhythmicContrast: 0.9915683
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Pin It Accessories
